//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEstandares3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VentasDetalle
    {
        public int Id { get; set; }
        public int Id_Documento { get; set; }
        public int Id_Almacen { get; set; }
        public int Id_Producto { get; set; }
        public int Cantidad { get; set; }
        public Nullable<decimal> Precio { get; set; }
        public Nullable<decimal> PrecioTotal { get; set; }
    
        public virtual Almacenes_Productos Almacenes_Productos { get; set; }
        public virtual Ventas Ventas { get; set; }
    }
}
